# Generated by Django 5.0.1 on 2025-11-20 17:38

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resume_file', models.FileField(help_text='PDF resume file', upload_to='resumes/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('job_description', models.TextField(help_text='Job description text')),
                ('resume_text', models.TextField(blank=True)),
                ('match_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('matching_skills', models.JSONField(blank=True, default=list)),
                ('matching_education', models.TextField(blank=True)),
                ('matching_experience', models.TextField(blank=True)),
                ('highlighted_strengths', models.JSONField(blank=True, default=list)),
                ('identified_gaps', models.JSONField(blank=True, default=list)),
                ('ai_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processing_time', models.FloatField(blank=True, help_text='Processing time in seconds', null=True)),
            ],
            options={
                'verbose_name': 'Analysis Session',
                'verbose_name_plural': 'Analysis Sessions',
                'ordering': ['-created_at'],
            },
        ),
    ]
