# Generated by Django 5.0.1 on 2025-11-26 16:44

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualifiedCandidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resume_file', models.FileField(help_text='PDF resume file of qualified candidate', upload_to='qualified_resumes/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('resume_text', models.TextField(help_text='Extracted resume text')),
                ('job_description', models.TextField(help_text='Job description text')),
                ('match_percentage', models.DecimalField(decimal_places=2, help_text='ATS match percentage (>80%)', max_digits=5)),
                ('matching_skills', models.JSONField(blank=True, default=list)),
                ('matching_education', models.TextField(blank=True)),
                ('matching_experience', models.TextField(blank=True)),
                ('highlighted_strengths', models.JSONField(blank=True, default=list)),
                ('identified_gaps', models.JSONField(blank=True, default=list)),
                ('qualification_date', models.DateTimeField(auto_now_add=True)),
                ('is_contacted', models.BooleanField(default=False, help_text='Has the candidate been contacted?')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the candidate')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('REVIEWED', 'Reviewed'), ('CONTACTED', 'Contacted'), ('INTERVIEWING', 'Interviewing'), ('HIRED', 'Hired'), ('REJECTED', 'Rejected')], default='NEW', help_text='Current status of the candidate', max_length=20)),
                ('analysis_session', models.OneToOneField(help_text='Reference to original analysis session', on_delete=django.db.models.deletion.CASCADE, related_name='qualified_candidate', to='analyzer.analysissession')),
            ],
            options={
                'verbose_name': 'Qualified Candidate',
                'verbose_name_plural': 'Qualified Candidates',
                'ordering': ['-match_percentage', '-qualification_date'],
                'indexes': [models.Index(fields=['-match_percentage'], name='analyzer_qu_match_p_1962cc_idx'), models.Index(fields=['status'], name='analyzer_qu_status_b699bd_idx'), models.Index(fields=['-qualification_date'], name='analyzer_qu_qualifi_33ff94_idx')],
            },
        ),
    ]
